# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Greet'
        # Default value if no value is explicitly provided
        default: 'hi'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Dependencies
      run: npm install && npm run build
    - name: Blazing fast GitHub Pages deploys
  # You may pin to the exact commit or the version.
  # uses: alex-page/blazing-fast-gh-pages-deploy@cd954d31df85a309bb5aa4a0a67cc2ac3512d722
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
    # The personal access token secret can be passed in using {{ secrets.GH_PAT }}
        repo-token: ${{ secrets.GH_PAT }}
    # The directory for the built website
        site-directory: _site
    # The branch to deploy the built website to
        deploy-branch: gh-pages
